import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Our Team — FAITH Foundation",
  description:
    "Meet the board and leadership of FAITH Foundation — Pastor Jeremiah L. Busby, Founding Minister, and Reid L. Whitesides, Housing Facilitator — serving Central Texas families.",
};

const BOARD = [
  {
    name: "Pastor Jeremiah L. Busby",
    role: "Founding Minister",
    initials: "JB",
    bio: [
      "Pastor Jeremiah L. Busby is the founding minister of FAITH Foundation and the spiritual heart of its mission. For years, Pastor Busby has answered a clear calling: to stand alongside families in their hardest moments and to turn faith into tangible help. It was this conviction — that no neighbor should have to face the loss of a home or a future alone — that led him to establish FAITH Foundation as a 501(c)(3) nonprofit serving Burnet and the wider Central Texas community.",
      "As Founding Minister, Pastor Busby sets the vision and values that guide everything the Foundation does. He shaped the organization around five enduring principles — Faith, Accountability, Instruction, Tenacity, and Hope — the very values that give the Foundation its name. Under his leadership, FAITH Foundation has remained rooted in compassion while holding itself to rigorous standards of stewardship and transparency, ensuring that every gift entrusted to the ministry produces real, measurable good in the lives of families.",
      "Pastor Busby believes deeply that housing stability and education are inseparable from human dignity. He has championed programs that pair direct housing assistance with practical instruction in financial literacy and life skills, so that families are not only helped through a crisis but equipped to build lasting independence. His pastoral approach — meeting people where they are, with patience and without judgment — has made FAITH Foundation a trusted presence for families of every background and belief.",
      "Beyond his administrative role, Pastor Busby remains a hands-on shepherd to the community he serves, offering counsel, encouragement, and a steady reminder that hope is always within reach. His tenacity in the face of difficult circumstances and his unwavering faith continue to inspire the volunteers, donors, and partners who make the Foundation's work possible.",
    ],
  },
  {
    name: "Reid L. Whitesides",
    role: "Housing Facilitator",
    initials: "RW",
    bio: [
      "Reid L. Whitesides serves as the Housing Facilitator for FAITH Foundation, where he leads the practical work of turning the organization's mission into stable homes for the families it serves. In this role, Reid is responsible for connecting families in need with the housing assistance that can keep them in their homes, and for building and maintaining the partnerships that fund that assistance.",
      "At the center of Reid's work is the Foundation's landmark partnership with Bright Box Homes — a sustainable model in which every home purchased generates a $2,500 donation to FAITH Foundation. Reid manages the flow of these gifts into housing vouchers, ensuring that the generosity generated by each home purchase reaches the families who need it most. It is a simple but powerful idea: when one family puts down roots in a new home, another family receives the support they need to keep theirs. Reid's stewardship makes that cycle of generosity possible.",
      "Reid brings a deep commitment to transparency and accountability to his role. He works directly with families to understand their circumstances, to navigate the path toward stable tenancy, and to pair housing support with the instruction families need to remain housed for the long term. He believes that lasting stability is built not through a single act of charity but through a relationship of trust, follow-through, and genuine care.",
      "Driven by the conviction that no neighbor should fall through the cracks, Reid approaches every case with tenacity and hope. Whether coordinating with partners, managing voucher resources, or walking a family through a difficult season, he embodies the Foundation's belief that affordable instruction and tenancy hope, offered together, can change the trajectory of a family for generations to come.",
    ],
  },
];

export default function TeamPage() {
  return (
    <>
      {/* Page header */}
      <section className="bg-gradient-to-b from-navy to-navy-light text-white">
        <div className="mx-auto max-w-4xl px-6 py-20 text-center">
          <span className="rounded-full border border-gold/60 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-gold">
            Our Team
          </span>
          <h1 className="mt-6 text-balance text-4xl font-extrabold leading-tight sm:text-5xl">
            The people behind the mission
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-white/85">
            FAITH Foundation is led by a dedicated board committed to serving
            Central Texas families with faith, accountability, and hope. Meet
            the leaders who make our work possible.
          </p>
        </div>
      </section>

      {/* Board bios */}
      <section className="bg-white">
        <div className="mx-auto max-w-5xl px-6 py-20">
          <h2 className="mb-3 text-center text-sm font-bold uppercase tracking-widest text-gold-dark">
            Board of Directors
          </h2>
          <h3 className="mb-12 text-center text-3xl font-extrabold text-navy">
            Leadership &amp; Board
          </h3>
          <div className="space-y-12">
            {BOARD.map((member) => (
              <article
                key={member.name}
                className="grid gap-8 rounded-2xl border border-navy/10 bg-gold/5 p-8 shadow-sm lg:grid-cols-[200px_1fr] lg:items-start"
              >
                <div className="flex flex-col items-center text-center">
                  <span
                    aria-hidden
                    className="flex h-28 w-28 items-center justify-center rounded-full bg-navy text-4xl font-extrabold text-gold"
                  >
                    {member.initials}
                  </span>
                  <h4 className="mt-4 text-xl font-bold text-navy">
                    {member.name}
                  </h4>
                  <p className="mt-1 text-sm font-semibold uppercase tracking-widest text-gold-dark">
                    {member.role}
                  </p>
                </div>
                <div className="space-y-4 text-lg leading-relaxed text-foreground/80">
                  {member.bio.map((paragraph, index) => (
                    <p key={index}>{paragraph}</p>
                  ))}
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-navy-dark text-white">
        <div className="mx-auto max-w-4xl px-6 py-16 text-center">
          <h2 className="mb-4 text-3xl font-extrabold">
            Stand with our team
          </h2>
          <p className="mx-auto mb-8 max-w-2xl text-lg leading-relaxed text-white/85">
            Your generosity gives our team the resources to keep families
            learning and keep families housed across Central Texas.
          </p>
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
            <Link
              href="/donate"
              className="rounded-md bg-gold px-8 py-3 text-base font-bold text-navy shadow-lg transition-colors hover:bg-gold-light"
            >
              Donate Now
            </Link>
            <Link
              href="/about"
              className="rounded-md border-2 border-gold px-8 py-3 text-base font-bold text-gold transition-colors hover:bg-gold hover:text-navy"
            >
              Learn About Us
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
